// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChly8GJlEi110QaxpUU3pRvcZebw1ahT8',
    appId: '1:658258724893:web:e7e4a474e66e25a2d81ef4',
    messagingSenderId: '658258724893',
    projectId: 'communityconnect-eb5e1',
    authDomain: 'communityconnect-eb5e1.firebaseapp.com',
    storageBucket: 'communityconnect-eb5e1.firebasestorage.app',
    measurementId: 'G-55ZQ59G6QJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrDjWagSH4r2TLg5J4LSjWey-d0BUnoYk',
    appId: '1:658258724893:android:3610d46175767e02d81ef4',
    messagingSenderId: '658258724893',
    projectId: 'communityconnect-eb5e1',
    storageBucket: 'communityconnect-eb5e1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP_MHWf6yH0L5E3dAU1TTJb8SbMSgTZuw',
    appId: '1:658258724893:ios:1ba4090c641c527fd81ef4',
    messagingSenderId: '658258724893',
    projectId: 'communityconnect-eb5e1',
    storageBucket: 'communityconnect-eb5e1.firebasestorage.app',
    iosBundleId: 'com.communityconnect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP_MHWf6yH0L5E3dAU1TTJb8SbMSgTZuw',
    appId: '1:658258724893:ios:e01389c8d840ec48d81ef4',
    messagingSenderId: '658258724893',
    projectId: 'communityconnect-eb5e1',
    storageBucket: 'communityconnect-eb5e1.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChly8GJlEi110QaxpUU3pRvcZebw1ahT8',
    appId: '1:658258724893:web:724ecd321fcbb93ed81ef4',
    messagingSenderId: '658258724893',
    projectId: 'communityconnect-eb5e1',
    authDomain: 'communityconnect-eb5e1.firebaseapp.com',
    storageBucket: 'communityconnect-eb5e1.firebasestorage.app',
    measurementId: 'G-95V8GW15FG',
  );
}
